### ISSUE TITLE
Switch from postfix to qmail

### ISSUE THREAD

**Issue by taoeffect** [taoeffect/empress#69]
[qmail](http://cr.yp.to/qmail.html) is more secure and stable than postfix. It also supports the [ezmlm](http://cr.yp.to/ezmlm.html) mailing list software by the same author (legendary DJB), which today blew my mind away with its ability to handle bounced emails.

Thoughts/feedback on this idea welcome.

**Comment by bgw** [comment]
qmail isn't actively developed anymore, and [hasn't been since 1998](http://www.lifewithqmail.org/lwq.html#history). There are forks of it (which is what Debian uses), but postfix is significantly better maintained, and likely does a better job of dealing with the modern web.

Additionally, postfix's design considers the privilege separation, strong input validation, and other design qualities that made qmail secure. The enemy here isn't postfix. It's sendmail.

I'd be open to integrating [OpenSMTP](https://www.opensmtpd.org/) if you'd like to move to a smaller, more lightweight SMTP implementation, but it's still a young project, and I don't know if it provides all the features we need yet.

If you want to support mailing lists, [librelist](http://librelist.com/) might be a good starting point, as would [GNU Mailman 3.x](https://mail.python.org/pipermail/mailman-announce/2014-April/000191.html). In fact, as mailing lists tend not to have the same privacy issues, we may consider mailing lists something we don't want to tackle, as the hosted version of librelist does a great job at it already.

**Comment by taoeffect** [comment]
Hmm.. some of this sounds familiar to me, we probably discussed this a while ago and came to the same conclusion. Oh well, it's a shame qmail isn't actively maintained, and that's kinda a deal breaker.

Thanks for the thoughts & comment!
