### ISSUE TITLE
Fix backports pinning.

### ISSUE THREAD

**Issue by taoeffect** [taoeffect/empress#7]
Some packages should be installed from backports or unstable. Nginx is a good candidate, since the version in stable is ancient.

However, as per our experiments installing `emacs24-nox` from backports, we need to make sure that we have the right pinning, otherwise the installation seems to not work. The pin should be equivalent to whatever is the default for stable (I think) to fix this.

Empress can copy over a file into `/etc/apt/preferences.d` to enforce this.

**Comment by bgw** [comment]
You don't need to set pinning for backports:

> [All backports are deactivated by default (i.e. the packages are pinned to 100 by using ButAutomaticUpgrades: yes in the Release files.](http://backports.debian.org/Instructions/)

`emacs24-nox` only had issues because the test server had mixed packages from unstable.

At this point, I'm thinking it might actually be best to remove the "niceties" stuff, since this is email focused. Same with removing the "default user". If someone wants to set that up, they should do it themselves or with a different script.
